export type TAG_KEY =
  | 'Baseweb'
  | 'Bootstrap'
  | 'Figma'
  | 'GitHub'
  | 'Golang'
  | 'Google Cloud'
  | 'JavaScript'
  | 'Mapbox'
  | 'MUI'
  | 'MySQL'
  | 'Next.js'
  | 'PowerShell'
  | 'React'
  | 'React Native'
  | 'Redux'
  | 'Repository'
  | 'Spotify API'
  | 'Tailwind CSS'
  | 'TypeScript'
  | 'Vercel';
